# This is a basic workflow to help you get started with Actions

name: Lambdabuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout stage
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      - name: "Configure AWS Credentials"
        # You may pin to the exact commit or the version.
        # uses: aws-actions/configure-aws-credentials@0309c38ebd10f90dfbb3889431bcf4ea38088012
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # optional
          # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # optional
          # AWS Region, e.g. us-east-2
          aws-region: eu-west-1
          
      - name: HashiCorp - Setup Terraform
        # You may pin to the exact commit or the version.
        # uses: hashicorp/setup-terraform@d22444889af304a44b997011fbabb81ff705a7b4
        uses: hashicorp/setup-terraform@v1
     
      #- name: Terraform fmt
       # run: terraform fmt
        #continue-on-error: true
       # working-directory: terraform-aws-lambda/examples/simple
        
      - name: Terraform init
        run: terraform init
        working-directory: ../../examples/triggers/
      
      - name: Terraform validate
        run: terraform validate -no-color
        working-directory: ../../examples/triggers/
        
      - name: Terraform plan
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: ../../examples/triggers/
        
      - name: Terraform apply
        run: terraform apply -no-color -auto-approve
        continue-on-error: true
        working-directory: ../../examples/triggers/
